Repository romie-gr/romie, pull requests merged in 2020-11, with the labels that each got.

#76 ci: add nfpm configuration to goreleaser for deb/rpm/apk
  .goreleaser.yml
Labels: size/L

#87 ci: Set up retroarch on Ubuntu runner
  .github/workflows/build.yml
Labels: size/XS

#81 [WIP] Documentation using Mkdocs
  .github/workflows/build.yml
  .github/workflows/publish_docs.yml
  Makefile
  docs/contributing.md
  docs/index.md
  mkdocs.yml
Labels: size/M

#86 ci: Add checksum workflow and remove whitespaces
  .goreleaser.yml
Labels: size/S
