Repository romie-gr/romie, pull requests merged in 2020-10, with the labels that each got.

#59 Replace pull_request with pull_request_target
  .github/workflows/auto-author-assign.yml
Labels: size/S

#60 [DOC] Initial release of LICENSE and NOTICE
  AUTHORS
  LICENSE
  NOTICE
  main.go
Labels: size/L

#61 Minor fixes and adding missing workflow file
  .github/workflows/gorelease.yml
  .goreleaser.yml
Labels: size/M

#62 Cerebrux/issue16
  .github/workflows/gorelease.yml
  .goreleaser.yml
Labels: size/L

#54 Initial Makefile
  .gitignore
  .golangci.yml
  Makefile
  go.mod
  go.sum
  main.go
  tools.go
Labels: size/L

#57 Create .goreleaser.yml
  .github/workflows/gorelease.yml
  .goreleaser.yml
Labels: size/M

#68 👷 ci: Add github action to validate goreleaser config
  .github/workflows/validate_goreleaser.yml
Labels: CI/CD, size/M

#70 👷 ci: Add dependabot config
  .github/dependabot.yml
Labels: CI/CD, size/S

#63 Build and Test for the CI
  .gitattributes
  .github/workflows/build.yml
  .gitignore
  Makefile
  main.go
  tools.go
Labels: size/M

#67 Build multi-platform bins for Linux, Mac Windows
  .goreleaser.yml
Labels: size/S

#72 👷 ci: Add mergify configuration, to automatically merge PRs
  .github/mergify.yml
Labels: size/M

#69 ci: add semantic.yml for semantic commits
  .github/workflows/semantic.yml
Labels: size/S

#79 fix: Move semantic.yml to its corresponding location, outside of actions dir 🐛
  .github/semantic.yml
Labels: CI/CD, bug

#78 ci: Add config for todo bot, to convert ToDo's to issues 👷
  .github/config.yml
Labels: size/XS

#74 ci: 👷 Add action to automate go mod tidy
  .github/workflows/go-mod-tidy.yml
Labels: size/M

#80 ci: Build and publish container image
  .github/workflows/gorelease.yml
  .goreleaser.yml
  Dockerfile
Labels: size/S

#85 docs: Create README.md and add goreportcard badge to it
  README.md
Labels: size/S
